CREATE TABLE Player(Login VARCHAR(50) PRIMARY KEY, Password CHAR(32) NOT NULL, FirstName VARCHAR(255) NOT NULL, LastName VARCHAR(255) NOT NULL, Phone INTEGER);
CREATE TABLE Team(TeamId INTEGER NOT NULL AUTO_INCREMENT, TeamName VARCHAR(50), TeamOwner VARCHAR(50), FOREIGN KEY (TeamOwner) REFERENCES Player(Login), PRIMARY KEY(TeamId));
CREATE TABLE PlaysFor(Login VARCHAR(50), FOREIGN KEY (Login) REFERENCES Player (Login), TeamID INTEGER, FOREIGN KEY (TeamId) REFERENCES Team(TeamId), PRIMARY KEY (Login, TeamId));
CREATE TABLE League(LeagueId INTEGER NOT NULL AUTO_INCREMENT, LeagueName VARCHAR(50), LeagueOwner VARCHAR(50), FOREIGN KEY (LeagueOwner) REFERENCES Player (Login), PRIMARY KEY (LeagueId));
CREATE TABLE TeamBelongsTo(TeamId INTEGER, FOREIGN KEY (TeamId) REFERENCES Team (TeamId), LeagueId INTEGER, FOREIGN KEY(LeagueId) REFERENCES League (LeagueId), PRIMARY KEY (TeamId, LeagueId));
CREATE TABLE Tournament(TournamentId INTEGER NOT NULL AUTO_INCREMENT, TournamentName VARCHAR (50), LeagueId INTEGER, Description VARCHAR(255), PRIMARY KEY (TournamentId), FOREIGN KEY (LeagueId) REFERENCES League (LeagueId));
CREATE TABLE Event(EventId INTEGER NOt NULL AUTO_INCREMENT, EventName VARCHAR (50), StartDate DATETIME NOT NULL, EndDate DATETIME, TournamentId INTEGER, FOREIGN KEY (TournamentId) REFERENCES Tournament (TournamentId), PRIMARY KEY(EventId));
CREATE TABLE TeamEvent(EventId INTEGER, FOREIGN KEY (EventId) REFERENCES Event (EventId), TeamId INTEGER, FOREIGN KEY (TeamId) REFERENCES Team (TeamId));
CREATE TABLE PlayerEvent(EventId INTEGER, FOREIGN KEY (EventId) REFERENCES Event (EventId), Login VARCHAR (50), FOREIGN KEY (Login) REFERENCES Player (Login));
